name: awqat
description: "Islamic prayer times app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^15.1.2
  adhan_dart: ^1.1.2
  shared_preferences: ^2.5.3
  geolocator: ^13.0.4
  geocoding: ^4.0.0
  lat_lng_to_timezone: ^0.2.0
  hijri: ^3.0.0
  flutter_qiblah: ^3.1.0+1
  flutter_compass_v2: ^1.0.3
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  package_info_plus: ^10.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  integration_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true

  image: "assets/app_icon/app_icon_960_foreground.png"

  color: "#000000"

  android_12:
    color: "#000000"

flutter_launcher_icons:
  image_path: "assets/app_icon/app_icon_960.png"

  android: true
  ios: true
  remove_alpha_ios: true

  adaptive_icon_background: "assets/app_icon/app_icon_960_background.png"
  adaptive_icon_foreground: "assets/app_icon/app_icon_960_foreground.png"

flutter:
  uses-material-design: true
  generate: true
